---
title: "Untitled"
author: "Nick Reich"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Key idea summary

1. We propose a framework for thinking about predictability in the context of infectious disease: bounding predictability by the hindcast error and a climatological model (which itself is either a seasonal or an "all previous observations" model, whichever has the lower error)

2. A horizon-limit of predictability can be thought of (a la Lorenz) as the prediction horizon at which the score from an analogue-based model equals or exceeds the error from the climatology model. This has the disadvantage of us knowing that the analogues are not the "perfect" model, but if we apply the same model consistently across multiple disease settings with roughly the same amount of training data then at least the relative ("this disease can be predicted at longer horizons than that one") should  be accurate. And the method of analogues, while computationally challenging for high dimensions, has a good theoretical footing: if something is predictable then it is predictable because we've seen instances like it in previous observations.

3. The lowest error achieveable by a model varies by factors specific to the setting (data source, season and location) and also possibly by the evaluation chosen (e.g., eval metric and scale of data). We can compute that limit and then run a regression to see which of those three features explain the most variation in the limits.

4. How sensitive are our calculations of lowest achievable error to our choice of metric and the scale of the data? (e.g., we use R^2 (essentially scaled MSE for point forecasts) and natural scale, but what if we used log-scale data, or a different metric than MSE, like a probabilistic forecast score, or entropy?)? The ideas of bounds would still apply.

## Inputs for tooling

- time-series of data
- probabilistic, boolean statement of probabilistic predictions or not, default to FALSE
- hindcast algorithm, default to trendfilter
- MOA algorithm, default to KCDE
- seasonal model algorithm, default to KCDE with seasonal-only covariates
- any-previous-observation algorithm, default to KDE on all previous observations
- metric, default to "RMSE"
- data transformation, default to "none"

Code needs
 - 

## Definitions

theta_

## Key analyses

1. Establish properties of the proposed predictability metric. Controlled experiments can determine empirical properties and performance of the proposed metric. Pick settings where the denominator of the skill calculation will be > 0.
    - Not this example: too trivial. For an entirely deterministic system (e.g. a sin curve) with annual seasonality, does an MOA approach indicate perfect prediction skill? This should be trivial to show. Hindcast, climatology and MOA error should all be zero. --> trivially perfect skill, although denominator of skill score might be unstable close to zero.
    - For an entirely deterministic system (e.g. a sin curve) with periodicity that does not align with annual cycles, we should see nonzero climatology error, but hindcast error should be zero. MOA error should also be zero. --> perfect skill 
    - Simulate a random walk with short-term memory (does such a thing exist? or an AR-2). This might show some short-term predictability so climatology > MOA > hindcast error.


2. Additional explorations of properties of skill calculation if time allows.
  - For the above experiments, how much data (how many seasons) does the metric need to make the determination?
  - Does some scaling of the data prior to computing the metric make it comparable across data that have different scales?


3. predictability EDA: flu, state-level in US
    - compute errors for HC, MOA and CLIM for ILINet data at state-level in the US
    - point predictions: 
        - hindcast: trendfilter
        - MOA: nearest neighbors
        - seasonal: nearest neighbors seasonal
        - any-previous-obs: permutation-based of all observations
        - metric: RMSE
        - data transformation: none
    - probabilistic predictions
        - hindcast: ??
        - MOA: KCDE
        - seasonal: KCDE seasonal
        - any-previous-obs: KDE
        - metric: log-score
        - data transformation: none
    - separate pair of figures/analyses for each point and probabilistic forecasts
        - what is the distribution of HC and CLIM error? how much variation is there in the spread between the two across locations? Could have a figure where x-axis is location (sorted by high-to-low hindcast error) and the y-axis is RMSE. For each location, we plot a line segment connecting the climatology error to the hindcast error to show the spread across locations.
        - what is the distribution of skill of MOA stratified by horizon? how much variation is there across locations? what are the predictions limits by horizon? Similar figure to above, but faceted vertically by horizon, scaled so for each location 1 is climatology error and 0 is hindcast error and then showing the average MOA error (across all studied seasons) between them for each state.


4. Ultimate goal: repeat the above analyses (probably choosing one of either point or probabilistic analyses) for horizons 1-10 weeks for a number of different disease/data source pairs and plot connected lines where x-axis is horizon, y-axis is skill. Color could be disease (e.g, flu datasets all are orange). Hypothesis is that skill decreases as a function of horizon, potentially getting below zero.
